import initScrollSuave from './modules/scroll-suave.js';
import initAnimacaoScroll from './modules/scroll-animacao.js';
import initAccordion from './modules/accordion.js';
import initTabNav from './modules/tabnav.js';
import initModal from './modules/modal.js';
import initMenuMobile from './modules/menu-mobile.js';
import initAnimaNumeros from './modules/anima-numeros.js';
import initRotate from './modules/txt-rotate.js';
import initFuncionamento from './modules/funcionamento.js';
import initSlideEsp from './modules/slide-especialidades.js';

initScrollSuave();
initAnimacaoScroll();
initAccordion();
initTabNav();
initModal();
initMenuMobile();
initAnimaNumeros();
initRotate();
initFuncionamento();
initSlideEsp();
